services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      -e POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    restart: always
    environment:
      - PYTHONPATH=/app
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}
    command: >
      sh -c "python wait_for_db.py && 
             python seed_script.py && 
             python -m app.init_admin && 
             gunicorn --bind 0.0.0.0:5000 --workers 3 app:app"
    depends_on:
      - db

  front:
    build:
      context: ./front
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - api
      
volumes:
  pgdata: