services:
  db:
    image: postgres:15-alpine
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app
      - DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}
    command: >
      sh -c "python wait_for_db.py &&
             python seed_script.py &&
             python -m app.init_admin &&
             gunicorn --bind 0.0.0.0:5000 --workers 3 app:app"
    depends_on:
      - db

  front:
    build:
      context: ./front
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env
    depends_on:
      - api

volumes:
  pgdata:
