server {
    listen 80;
    
    # La carpeta donde pusimos los archivos estáticos
    root /usr/share/nginx/html;
    index index.html index.htm;

    location / {
        # Esta línea es MAGIA para Single Page Apps (React, Vue, etc):
        # Intenta servir el archivo solicitado ($uri), si no existe,
        # sirve el index.html (para que el router de JS maneje la URL).
        try_files $uri $uri/ /index.html;
    }

    # Configuración opcional para cachear archivos estáticos
    location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg)$ {
        expires 1y;
        add_header Cache-Control "public, no-transform";
    }
}